version: '3.9'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: mynotepad
      POSTGRES_PASSWORD: mynotepad_password
      POSTGRES_DB: mynotepad
    ports:
      - "5432:5432"
    volumes:
      - ./docker-conf/postgres/:/var/lib/postgresql/data
    networks:
      default:
    
  rabbit_mq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    networks:
      default:



networks:
  default:
    driver: bridge